language: nix
nix: 2.3.4

env:
  global:
    - CACHIX_CACHE=nprindle

install:
  - nix --version
  - travis_retry nix-channel --update
  - nix-env -iA cachix -f https://cachix.org/api/v1/install
  - cachix use "${CACHIX_CACHE}"

script:
  - nix build

deploy:
  provider: pages
  token: $GITHUB_TOKEN
  project_name: blog
  cleanup: false
  keep_history: true
  on:
    branch: main
  target_branch: gh-pages
  # Travis will fail after deployment if using a symlink directly
  local_dir: "$(readlink result)"

